# This is a basic workflow to help you get started with Actions

name: Create Azure OpenAI Workspace

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  CreateAzureOpenAIWorkspace:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Azure Login
        uses: Azure/login@v1.4.2
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
      - name: Azure CLI Action
        uses: Azure/cli@v1.0.7
        with:
          # Specify the script here
          inlineScript: |
            az group create --name ${{secrets.rg}} --location name ${{secrets.location}} 
            
            az cognitiveservices account create \
              -n ${{secrets.srvcname}} \
              -g ${{secrets.rg}} \
              -l ${{secrets.location}} \
              --kind OpenAI \
              --sku s0 \
              --subscription ${{secrets.subscription}}
            
            az cognitiveservices account deployment create \
            -g ${{secrets.rg}} \
            -n ${{secrets.srvcname}} \
              --deployment-name MyModel \
              --model-name ${{secrets.modelname}} \
              --model-version "1"  \
              --model-format OpenAI \
              --scale-settings-scale-type "Standard"
          
          

